//go:build linux

package sshagent

import (
	"bytes"
	"testing"

	"github.com/user/kpxcd/internal/config"
)

// TestGenerateTestKeyForAllTypes verifies that GenerateTestKey works
// for rsa, ed25519, and ecdsa-p256 key types.
func TestGenerateTestKeyForAllTypes(t *testing.T) {
	keyTypes := []string{"rsa", "ed25519", "ecdsa-p256"}

	for _, kt := range keyTypes {
		t.Run(kt, func(t *testing.T) {
			key, err := GenerateTestKey(kt)
			if err != nil {
				t.Fatalf("GenerateTestKey(%q) failed: %v", kt, err)
			}
			if key == nil {
				t.Fatal("GenerateTestKey returned nil")
			}
			if key.Signer == nil {
				t.Error("Signer is nil")
			}
			if len(key.Blob) == 0 {
				t.Error("Blob is empty")
			}
			if key.Format == "" {
				t.Error("Format is empty")
			}
			// Verify the comment follows the expected pattern.
			expectedComment := "test@" + kt
			if key.Comment != expectedComment {
				t.Errorf("Comment = %q, want %q", key.Comment, expectedComment)
			}
		})
	}
}

// TestGenerateTestKeyUnsupportedType verifies that GenerateTestKey
// returns an error for unsupported key types.
func TestGenerateTestKeyUnsupportedType(t *testing.T) {
	_, err := GenerateTestKey("unsupported")
	if err == nil {
		t.Fatal("expected error for unsupported key type, got nil")
	}
}

// TestKeyFingerprint verifies that Key.Fingerprint returns a SHA256
// fingerprint in the correct format.
func TestKeyFingerprint(t *testing.T) {
	key, err := GenerateTestKey("ed25519")
	if err != nil {
		t.Fatalf("GenerateTestKey failed: %v", err)
	}

	fp := key.Fingerprint()

	// Should start with "SHA256:".
	if len(fp) < 7 || fp[:7] != "SHA256:" {
		t.Errorf("fingerprint = %q, should start with SHA256:", fp)
	}

	// Should be consistent across multiple calls.
	fp2 := key.Fingerprint()
	if fp != fp2 {
		t.Errorf("fingerprint not consistent: %q vs %q", fp, fp2)
	}

	// Two different keys should have different fingerprints.
	key2, err := GenerateTestKey("ed25519")
	if err != nil {
		t.Fatalf("GenerateTestKey failed: %v", err)
	}
	fp3 := key2.Fingerprint()
	if fp == fp3 {
		t.Error("different keys should have different fingerprints")
	}
}

// TestKeyFingerprintEmpty verifies that Fingerprint handles empty blob.
func TestKeyFingerprintEmpty(t *testing.T) {
	key := &Key{Blob: nil}
	fp := key.Fingerprint()
	if fp != "SHA256:(empty)" {
		t.Errorf("fingerprint for empty blob = %q, want SHA256:(empty)", fp)
	}

	key2 := &Key{Blob: []byte{}}
	fp2 := key2.Fingerprint()
	if fp2 != "SHA256:(empty)" {
		t.Errorf("fingerprint for empty byte slice = %q, want SHA256:(empty)", fp2)
	}
}

// TestKeyEqual verifies that Key.Equal correctly compares keys by fingerprint.
func TestKeyEqual(t *testing.T) {
	key, err := GenerateTestKey("ed25519")
	if err != nil {
		t.Fatalf("GenerateTestKey failed: %v", err)
	}

	// A key should equal itself.
	if !key.Equal(key) {
		t.Error("key should equal itself")
	}

	// Create a copy with same blob — should be equal.
	key2 := &Key{
		Blob:  make([]byte, len(key.Blob)),
		Comment: key.Comment,
	}
	copy(key2.Blob, key.Blob)
	if !key.Equal(key2) {
		t.Error("keys with same blob should be equal")
	}

	// Different key — should not be equal.
	key3, err := GenerateTestKey("ed25519")
	if err != nil {
		t.Fatalf("GenerateTestKey failed: %v", err)
	}
	if key.Equal(key3) {
		t.Error("different keys should not be equal")
	}

	// nil == nil should be true.
	var nilKey *Key
	if !nilKey.Equal(nilKey) {
		t.Error("nil should equal nil")
	}

	// nil vs non-nil should be false.
	if key.Equal(nil) {
		t.Error("non-nil key should not equal nil")
	}
	if nilKey.Equal(key) {
		t.Error("nil key should not equal non-nil key")
	}
}

// TestParsePrivateKeyEd25519 verifies that ParsePrivateKey can parse
// an Ed25519 key generated by crypto/ed25519, marshaled to OpenSSH format.
func TestParsePrivateKeyEd25519(t *testing.T) {
	key, err := GenerateTestKey("ed25519")
	if err != nil {
		t.Fatalf("GenerateTestKey failed: %v", err)
	}

	// Verify the parsed key has correct properties.
	if key.Format != "ssh-ed25519" {
		t.Errorf("Format = %q, want ssh-ed25519", key.Format)
	}
	if key.Signer == nil {
		t.Fatal("Signer is nil after GenerateTestKey")
	}

	// Verify the public key is valid.
	sshPub := key.Signer.PublicKey()
	if sshPub == nil {
		t.Fatal("PublicKey from signer is nil")
	}
	if sshPub.Type() != "ssh-ed25519" {
		t.Errorf("public key type = %q, want ssh-ed25519", sshPub.Type())
	}

	// Verify we can sign data with the parsed key.
	data := []byte("test signing data")
	sig, err := key.Sign(data)
	if err != nil {
		t.Fatalf("Sign failed: %v", err)
	}
	if sig == nil || len(sig.Blob) == 0 {
		t.Error("signature is empty")
	}

	// Verify the signature can be validated with the public key.
	if err := sshPub.Verify(data, sig); err != nil {
		t.Fatalf("signature verification failed: %v", err)
	}
}

// TestParsePrivateKeyInvalidData verifies that ParsePrivateKey returns
// an error for invalid key data.
func TestParsePrivateKeyInvalidData(t *testing.T) {
	_, err := ParsePrivateKey([]byte("not a valid key"), "")
	if err == nil {
		t.Fatal("expected error for invalid key data, got nil")
	}
}

// TestIdentityManagerAddRemoveListFindByFingerprint verifies the
// IdentityManager Add, Remove, List, and FindByFingerprint operations.
func TestIdentityManagerAddRemoveListFindByFingerprint(t *testing.T) {
	cfg := &config.SSHAgentConfig{}
	im := NewIdentityManager(cfg)

	if im == nil {
		t.Fatal("NewIdentityManager returned nil")
	}

	// Count should start at 0.
	if im.Count() != 0 {
		t.Errorf("expected 0 keys, got %d", im.Count())
	}

	// Generate and add a key.
	key1, err := GenerateTestKey("ed25519")
	if err != nil {
		t.Fatalf("GenerateTestKey failed: %v", err)
	}

	err = im.AddIdentity(key1, 0, false, false, "db-uuid-1", "entry-uuid-1")
	if err != nil {
		t.Fatalf("AddIdentity failed: %v", err)
	}

	if im.Count() != 1 {
		t.Errorf("expected 1 key after add, got %d", im.Count())
	}

	// List should return the key.
	listed := im.ListIdentities()
	if len(listed) != 1 {
		t.Fatalf("expected 1 key in list, got %d", len(listed))
	}
	if listed[0].Key.Fingerprint() != key1.Fingerprint() {
		t.Error("listed key fingerprint does not match")
	}

	// FindByFingerprint should find the key.
	fp := key1.Fingerprint()
	found := im.FindIdentityByFingerprint(fp)
	if found == nil {
		t.Fatal("FindIdentityByFingerprint returned nil for existing key")
	}
	if found.DBUUID != "db-uuid-1" {
		t.Errorf("DBUUID = %q, want db-uuid-1", found.DBUUID)
	}
	if found.EntryUUID != "entry-uuid-1" {
		t.Errorf("EntryUUID = %q, want entry-uuid-1", found.EntryUUID)
	}

	// Remove the key.
	err = im.RemoveIdentity(fp)
	if err != nil {
		t.Fatalf("RemoveIdentity failed: %v", err)
	}

	if im.Count() != 0 {
		t.Errorf("expected 0 keys after remove, got %d", im.Count())
	}

	// FindByFingerprint should return nil after removal.
	found = im.FindIdentityByFingerprint(fp)
	if found != nil {
		t.Error("FindIdentityByFingerprint should return nil after removal")
	}
}

// TestIdentityManagerRemoveNonexistentKey verifies that removing a
// nonexistent key returns an error.
func TestIdentityManagerRemoveNonexistentKey(t *testing.T) {
	cfg := &config.SSHAgentConfig{}
	im := NewIdentityManager(cfg)

	err := im.RemoveIdentity("nonexistent-fingerprint")
	if err == nil {
		t.Fatal("expected error when removing nonexistent key, got nil")
	}
}

// TestIdentityManagerAddMultipleKeys verifies adding and listing
// multiple keys.
func TestIdentityManagerAddMultipleKeys(t *testing.T) {
	cfg := &config.SSHAgentConfig{}
	im := NewIdentityManager(cfg)

	keyTypes := []string{"rsa", "ed25519", "ecdsa-p256"}

	for i, kt := range keyTypes {
		key, err := GenerateTestKey(kt)
		if err != nil {
			t.Fatalf("GenerateTestKey(%q) failed: %v", kt, err)
		}
		err = im.AddIdentity(key, uint32(i*60), false, true, "db-uuid", "entry-uuid")
		if err != nil {
			t.Fatalf("AddIdentity failed: %v", err)
		}
	}

	if im.Count() != 3 {
		t.Errorf("expected 3 keys, got %d", im.Count())
	}

	// All keys should be findable.
	listed := im.ListIdentities()
	for _, lk := range listed {
		found := im.FindIdentityByFingerprint(lk.Key.Fingerprint())
		if found == nil {
			t.Errorf("key with fingerprint %q not found after listing", lk.Key.Fingerprint())
		}
	}
}

// TestIdentityManagerRemoveAllIdentities verifies that RemoveAllIdentities
// clears all keys.
func TestIdentityManagerRemoveAllIdentities(t *testing.T) {
	cfg := &config.SSHAgentConfig{}
	im := NewIdentityManager(cfg)

	// Add two keys.
	key1, _ := GenerateTestKey("rsa")
	key2, _ := GenerateTestKey("ed25519")
	_ = im.AddIdentity(key1, 0, false, false, "db1", "entry1")
	_ = im.AddIdentity(key2, 0, false, false, "db2", "entry2")

	if im.Count() != 2 {
		t.Fatalf("expected 2 keys, got %d", im.Count())
	}

	im.RemoveAllIdentities()

	if im.Count() != 0 {
		t.Errorf("expected 0 keys after RemoveAll, got %d", im.Count())
	}
}

// TestIdentityManagerAddReplacesExisting verifies that adding a key
// with the same fingerprint replaces the existing entry.
func TestIdentityManagerAddReplacesExisting(t *testing.T) {
	cfg := &config.SSHAgentConfig{}
	im := NewIdentityManager(cfg)

	key, err := GenerateTestKey("ed25519")
	if err != nil {
		t.Fatalf("GenerateTestKey failed: %v", err)
	}

	_ = im.AddIdentity(key, 0, false, false, "db-old", "entry-old")
	_ = im.AddIdentity(key, 300, true, true, "db-new", "entry-new")

	// Count should still be 1 (replaced, not duplicated).
	if im.Count() != 1 {
		t.Errorf("expected 1 key after replacement, got %d", im.Count())
	}

	found := im.FindIdentityByFingerprint(key.Fingerprint())
	if found == nil {
		t.Fatal("key not found after replacement")
	}
	if found.Lifetime != 300 {
		t.Errorf("Lifetime = %d, want 300", found.Lifetime)
	}
	if !found.Confirm {
		t.Error("Confirm should be true after replacement")
	}
	if found.DBUUID != "db-new" {
		t.Errorf("DBUUID = %q, want db-new", found.DBUUID)
	}
}

// TestIdentityManagerRemoveIdentitiesForDatabase verifies that keys
// belonging to a database can be removed.
func TestIdentityManagerRemoveIdentitiesForDatabase(t *testing.T) {
	cfg := &config.SSHAgentConfig{RemoveOnLock: true}
	im := NewIdentityManager(cfg)

	key1, _ := GenerateTestKey("ed25519")
	key2, _ := GenerateTestKey("rsa")

	// Add key1 with autoRemove=true for db1.
	_ = im.AddIdentity(key1, 0, false, true, "db1", "e1")
	// Add key2 with autoRemove=false for db1.
	_ = im.AddIdentity(key2, 0, false, false, "db1", "e2")

	if im.Count() != 2 {
		t.Fatalf("expected 2 keys, got %d", im.Count())
	}

	im.RemoveIdentitiesForDatabase("db1")

	// key1 should be removed (autoRemove=true), key2 should remain.
	if im.Count() != 1 {
		t.Errorf("expected 1 key after removal, got %d", im.Count())
	}

	found := im.FindIdentityByFingerprint(key2.Fingerprint())
	if found == nil {
		t.Error("key2 (autoRemove=false) should still exist")
	}
}

// TestLoadedKeyFields verifies that LoadedKey stores all fields correctly.
func TestLoadedKeyFields(t *testing.T) {
	cfg := &config.SSHAgentConfig{}
	im := NewIdentityManager(cfg)

	key, err := GenerateTestKey("ed25519")
	if err != nil {
		t.Fatalf("GenerateTestKey failed: %v", err)
	}

	err = im.AddIdentity(key, 120, true, true, "test-db", "test-entry")
	if err != nil {
		t.Fatalf("AddIdentity failed: %v", err)
	}

	found := im.FindIdentityByFingerprint(key.Fingerprint())
	if found == nil {
		t.Fatal("key not found")
	}

	if found.Lifetime != 120 {
		t.Errorf("Lifetime = %d, want 120", found.Lifetime)
	}
	if !found.Confirm {
		t.Error("Confirm should be true")
	}
	if !found.AutoRemove {
		t.Error("AutoRemove should be true")
	}
	if found.DBUUID != "test-db" {
		t.Errorf("DBUUID = %q, want test-db", found.DBUUID)
	}
	if found.EntryUUID != "test-entry" {
		t.Errorf("EntryUUID = %q, want test-entry", found.EntryUUID)
	}
	if !bytes.Equal(found.Key.Blob, key.Blob) {
		t.Error("Key blob mismatch")
	}
}

// TestKeySetters verifies the Key setter methods.
func TestKeySetters(t *testing.T) {
	key, err := GenerateTestKey("ed25519")
	if err != nil {
		t.Fatalf("GenerateTestKey failed: %v", err)
	}

	key.SetEntryUUID("entry-uuid-123")
	if key.EntryUUID() != "entry-uuid-123" {
		t.Errorf("EntryUUID = %q, want entry-uuid-123", key.EntryUUID())
	}

	key.SetDBUUID("db-uuid-456")
	if key.DBUUID() != "db-uuid-456" {
		t.Errorf("DBUUID = %q, want db-uuid-456", key.DBUUID())
	}

	key.SetComment("new-comment")
	if key.Comment != "new-comment" {
		t.Errorf("Comment = %q, want new-comment", key.Comment)
	}
}

// TestKeyPublicKey verifies that PublicKey returns a valid ssh.PublicKey.
func TestKeyPublicKey(t *testing.T) {
	key, err := GenerateTestKey("ed25519")
	if err != nil {
		t.Fatalf("GenerateTestKey failed: %v", err)
	}

	pub := key.PublicKey()
	if pub == nil {
		t.Fatal("PublicKey returned nil")
	}
	if pub.Type() != "ssh-ed25519" {
		t.Errorf("public key type = %q, want ssh-ed25519", pub.Type())
	}
}
